services:
      minio:
            image: quay.io/minio/minio
            container_name: minio
            ports:
                  - "9000:9000"
                  - "9001:9001"
            environment:
                  - MINIO_ROOT_USER=minioadmin    
                  - MINIO_ROOT_PASSWORD=minioadmin    
                  
            volumes:
                  - ~/minio/data:/data
            command: server /data --console-address ":9001"
            networks: 
              - safedriver_network

      safedriver-backend:
            build:
                  context: .
                  dockerfile: Dockerfile
            container_name: safedriver-backend
            ports:
                  - "8080:8080"
            command: /start.sh
            env_file:
                  - .env
            depends_on:
                  - driversafedb
                  - minio
            networks: 
              - safedriver_network

      driversafedb:
            image: postgres:16.6-alpine3.21
            container_name: driversafedb
            ports:
                  - "5432:5432"
            env_file:
                  - .env
            volumes:
                  - data:/var/lib/postgresql/data
            restart: always
            networks: 
              - safedriver_network


volumes:
      data:
            driver: local
networks:
  safedriver_network:
    driver: bridge