services:
    driversafedb:
          image: postgres:16.6-alpine3.21
          container_name: driversafedb
          ports:
            - "5432:5432"
          env_file:
            - .env
          volumes:
            - data:/var/lib/postgresql/data
          restart: always

volumes:
  data:
    driver: local